
-- Popular simulado_questions com 100 questões por nível (500 total)
-- Usa 10 arquétipos por nível replicados 10x com rótulo de variante

DELETE FROM public.simulado_questions;

WITH templates AS (
  SELECT * FROM (VALUES
    -- NÍVEL 1 — Fácil (ENAMED real)
    (1, 'facil', 'Clínica Médica', 'Hipertensão', 'Homem 55a, PA 160/100 em 3 aferições, assintomático, sem lesão órgão-alvo, TFG normal.', 'Qual a conduta inicial mais apropriada?',
     '[{"text":"MEV + iniciar IECA ou BRA","is_correct":true},{"text":"Internação para MAPA","is_correct":false},{"text":"Iniciar 3 drogas imediatamente","is_correct":false},{"text":"Apenas MEV sem medicação","is_correct":false},{"text":"Furosemida EV","is_correct":false}]'::jsonb,
     'HAS estágio 2 exige MEV + monoterapia (IECA/BRA, BCC ou tiazídico).'),
    (1, 'facil', 'Pediatria', 'Diarreia aguda', 'Criança 2a, diarreia aquosa 3d, mucosas levemente secas, diurese preservada, aceita VO.', 'Conduta?',
     '[{"text":"TRO com SRO","is_correct":true},{"text":"Hidratação EV imediata","is_correct":false},{"text":"ATB empírico","is_correct":false},{"text":"Loperamida","is_correct":false},{"text":"Dieta zero 24h","is_correct":false}]'::jsonb,
     'Desidratação leve → Plano A/B com SRO.'),
    (1, 'facil', 'GO', 'Pré-natal', 'Gestante 28 sem, TOTG75 com jejum 96.', 'Diagnóstico?',
     '[{"text":"DMG","is_correct":true},{"text":"Diabetes prévia","is_correct":false},{"text":"Normal","is_correct":false},{"text":"Hipoglicemia","is_correct":false},{"text":"HAS gestacional","is_correct":false}]'::jsonb,
     'Jejum ≥92 no TOTG75 = DMG.'),
    (1, 'facil', 'Med Família', 'Rastreio', 'Mulher 52a, assintomática, última mamografia há 3 anos normal.', 'Conduta (MS)?',
     '[{"text":"Mamografia bienal 50-69a","is_correct":true},{"text":"Anual a partir dos 40","is_correct":false},{"text":"Só se sintomas","is_correct":false},{"text":"USG mama","is_correct":false},{"text":"RM mamas","is_correct":false}]'::jsonb,
     'MS: mamografia bienal 50-69 anos.'),
    (1, 'facil', 'Saúde Coletiva', 'SUS', 'Princípio que garante atendimento a todos sem discriminação.', 'Qual princípio?',
     '[{"text":"Universalidade","is_correct":true},{"text":"Equidade","is_correct":false},{"text":"Integralidade","is_correct":false},{"text":"Descentralização","is_correct":false},{"text":"Hierarquização","is_correct":false}]'::jsonb,
     'Universalidade: acesso a todos.'),
    (1, 'facil', 'Saúde Mental', 'Depressão', 'Paciente 30a, 4 sem: anedonia, insônia, culpa, sem ideação.', 'Primeira linha?',
     '[{"text":"ISRS","is_correct":true},{"text":"Benzodiazepínico","is_correct":false},{"text":"TEC","is_correct":false},{"text":"Lítio","is_correct":false},{"text":"Antipsicótico","is_correct":false}]'::jsonb,
     'ISRS: primeira linha em TDM leve-moderado.'),
    (1, 'facil', 'Cirurgia Geral', 'Apendicite', 'Homem 22a, dor FID 24h, Blumberg+, leucocitose.', 'Conduta?',
     '[{"text":"Apendicectomia","is_correct":true},{"text":"ATB isolado","is_correct":false},{"text":"TC antes de tudo","is_correct":false},{"text":"Observação 48h","is_correct":false},{"text":"Alta com analgesia","is_correct":false}]'::jsonb,
     'Apendicite não complicada → apendicectomia.'),
    (1, 'facil', 'Clínica Médica', 'PAC', 'Paciente 40a, tosse, febre, consolidação lobar, CURB-65=0.', 'Tratamento?',
     '[{"text":"Amoxicilina VO ambulatorial","is_correct":true},{"text":"Ceftriaxona EV + UTI","is_correct":false},{"text":"Oseltamivir","is_correct":false},{"text":"Corticoide isolado","is_correct":false},{"text":"Alta sem ATB","is_correct":false}]'::jsonb,
     'PAC baixa gravidade → amoxicilina VO ambulatorial.'),
    (1, 'facil', 'Pediatria', 'Vacinação', 'RN filho de mãe HBsAg+.', 'Conduta nas primeiras 12h?',
     '[{"text":"Vacina hepatite B + imunoglobulina","is_correct":true},{"text":"Só vacina BCG","is_correct":false},{"text":"Só imunoglobulina","is_correct":false},{"text":"Aguardar 30 dias","is_correct":false},{"text":"Isolar RN","is_correct":false}]'::jsonb,
     'Profilaxia vertical HBV: vacina + HBIG em <12h.'),
    (1, 'facil', 'GO', 'Sangramento 3T', 'Gestante 32 sem, sangramento vermelho vivo indolor, útero normotônico.', 'Hipótese principal?',
     '[{"text":"Placenta prévia","is_correct":true},{"text":"DPP","is_correct":false},{"text":"Trabalho de parto","is_correct":false},{"text":"Rotura uterina","is_correct":false},{"text":"Vasa prévia","is_correct":false}]'::jsonb,
     'Sangramento indolor no 3T com útero normal = placenta prévia.'),

    -- NÍVEL 2 — Médio
    (2, 'medio', 'Clínica Médica', 'IC', 'Homem 68a, dispneia NYHA III, FEVE 30%, creat 1.2, K 4.2, em IECA.', 'Próximo passo?',
     '[{"text":"Adicionar betabloqueador","is_correct":true},{"text":"Suspender IECA","is_correct":false},{"text":"Adicionar digoxina","is_correct":false},{"text":"Furosemida em bolus","is_correct":false},{"text":"Espironolactona sem BB","is_correct":false}]'::jsonb,
     'ICFER: IECA + BB são pilares.'),
    (2, 'medio', 'Cirurgia', 'Perfuração', 'Idoso 72a, dor súbita difusa, abdome em tábua, pneumoperitônio.', 'Conduta?',
     '[{"text":"Laparotomia exploradora","is_correct":true},{"text":"Conservador com SNG","is_correct":false},{"text":"TC e alta","is_correct":false},{"text":"Endoscopia urgente","is_correct":false},{"text":"Colonoscopia","is_correct":false}]'::jsonb,
     'Perfuração → cirurgia imediata.'),
    (2, 'medio', 'GO', 'Pré-eclâmpsia grave', 'Gestante 36 sem, PA 160/110, proteinúria, cefaleia, visão turva.', 'Conduta?',
     '[{"text":"MgSO4 e interrupção","is_correct":true},{"text":"Expectante até termo","is_correct":false},{"text":"Diurético apenas","is_correct":false},{"text":"Captopril","is_correct":false},{"text":"Alta com MAPA","is_correct":false}]'::jsonb,
     'PE grave com iminência: MgSO4 + interrupção.'),
    (2, 'medio', 'Pediatria', 'Bronquiolite', 'Lactente 6m, sibilos, SatO2 93%, aceita mamadas, sem tiragem.', 'Conduta?',
     '[{"text":"Suporte e hidratação","is_correct":true},{"text":"ATB EV","is_correct":false},{"text":"Corticoide sistêmico","is_correct":false},{"text":"Broncodilatador de rotina","is_correct":false},{"text":"IOT imediata","is_correct":false}]'::jsonb,
     'Bronquiolite: suporte; ATB/corticoide não rotineiros.'),
    (2, 'medio', 'Med Família', 'DM2', 'Mulher 60a, DM2, HbA1c 8.5, IMC 31, sem DCV.', 'Primeira escolha?',
     '[{"text":"Metformina","is_correct":true},{"text":"Insulina basal","is_correct":false},{"text":"Sulfonilureia","is_correct":false},{"text":"Glitazona","is_correct":false},{"text":"Só dieta","is_correct":false}]'::jsonb,
     'Metformina: primeira linha em DM2.'),
    (2, 'medio', 'Saúde Coletiva', 'Epidemiologia', 'Estudo acompanha expostos e não expostos longitudinalmente.', 'Desenho?',
     '[{"text":"Coorte","is_correct":true},{"text":"Caso-controle","is_correct":false},{"text":"Transversal","is_correct":false},{"text":"Ecológico","is_correct":false},{"text":"Ensaio clínico","is_correct":false}]'::jsonb,
     'Acompanhamento longitudinal = coorte.'),
    (2, 'medio', 'Saúde Mental', 'Mania aguda', 'Paciente em mania aguda, sem comorbidades renais.', 'Primeira linha?',
     '[{"text":"Lítio ou valproato + antipsicótico","is_correct":true},{"text":"ISRS isolado","is_correct":false},{"text":"Benzo isolado","is_correct":false},{"text":"TEC inicial","is_correct":false},{"text":"Só psicoterapia","is_correct":false}]'::jsonb,
     'Mania aguda: estabilizador + antipsicótico.'),
    (2, 'medio', 'Clínica Médica', 'DPOC', 'Homem 70a, dispneia+expectoração purulenta, SatO2 85%, VEF1 40%.', 'Conduta?',
     '[{"text":"O2 controlado + BD + corticoide + ATB","is_correct":true},{"text":"Só O2 100%","is_correct":false},{"text":"Só BD","is_correct":false},{"text":"VNI em todos","is_correct":false},{"text":"Intubar imediatamente","is_correct":false}]'::jsonb,
     'Exacerbação DPOC: O2 alvo 88-92%, BD, corticoide e ATB.'),
    (2, 'medio', 'GO', 'Climatério', 'Mulher 52a, fogachos intensos, útero presente, sem CI.', 'Conduta?',
     '[{"text":"TH estrogênio+progesterona","is_correct":true},{"text":"TH só estrogênio","is_correct":false},{"text":"ISRS obrigatório","is_correct":false},{"text":"Tibolona sempre","is_correct":false},{"text":"Nada fazer","is_correct":false}]'::jsonb,
     'TH combinada em mulher com útero.'),
    (2, 'medio', 'Pediatria', 'Febre <3m', 'Lactente 2 meses, T 39, aspecto tóxico.', 'Conduta?',
     '[{"text":"Internação + HMC/LCR/urina + ATB empírico","is_correct":true},{"text":"Alta com antitérmico","is_correct":false},{"text":"Só urina","is_correct":false},{"text":"Aguardar 48h","is_correct":false},{"text":"Só exame físico","is_correct":false}]'::jsonb,
     '<3m com febre: investigação completa + ATB empírico.'),

    -- NÍVEL 3 — Difícil
    (3, 'dificil', 'Clínica Médica', 'IAMCSST', 'Homem 58a, dor precordial 2h, supra ST V2-V4, hemodinâmica <60min.', 'Conduta?',
     '[{"text":"Angioplastia primária","is_correct":true},{"text":"Trombólise imediata","is_correct":false},{"text":"Só AAS e observar","is_correct":false},{"text":"ECG seriado por 6h","is_correct":false},{"text":"CRM de urgência","is_correct":false}]'::jsonb,
     'IAMCSST com PCI <120min: angioplastia primária.'),
    (3, 'dificil', 'Cirurgia', 'Trauma', 'Politrauma hipotenso, FAST+ em abdome, mau responde a cristaloide.', 'Conduta?',
     '[{"text":"Laparotomia imediata","is_correct":true},{"text":"TC antes","is_correct":false},{"text":"Transfusão e observar","is_correct":false},{"text":"Drenagem torácica","is_correct":false},{"text":"Toracotomia","is_correct":false}]'::jsonb,
     'Choque hemorrágico + FAST+ → laparotomia.'),
    (3, 'dificil', 'GO', 'HELLP', 'Gestante 34 sem, HELLP completa com dor HCD.', 'Conduta?',
     '[{"text":"MgSO4 + corticoide + interrupção","is_correct":true},{"text":"Expectante até 37 sem","is_correct":false},{"text":"Plasmaférese","is_correct":false},{"text":"Heparina","is_correct":false},{"text":"Só anti-hipertensivo","is_correct":false}]'::jsonb,
     'HELLP: estabilizar e interromper.'),
    (3, 'dificil', 'Pediatria', 'Sepse pediátrica', 'Criança 3a, choque séptico na 1ª hora.', 'Conduta?',
     '[{"text":"Cristaloide 20ml/kg + ATB amplo em 1h","is_correct":true},{"text":"Só antitérmico","is_correct":false},{"text":"Aguardar culturas","is_correct":false},{"text":"Corticoide isolado","is_correct":false},{"text":"Dopamina direta","is_correct":false}]'::jsonb,
     'Hora de ouro: volume + ATB + culturas.'),
    (3, 'dificil', 'Med Família', 'Dor torácica', 'Homem 45a, dor atípica, ECG e troponina normais, HAS+DM.', 'Conduta?',
     '[{"text":"Estratificação não invasiva","is_correct":true},{"text":"Alta sem retorno","is_correct":false},{"text":"Cateterismo direto","is_correct":false},{"text":"Só AAS","is_correct":false},{"text":"Ansiolítico","is_correct":false}]'::jsonb,
     'Risco intermediário: estratificação não invasiva.'),
    (3, 'dificil', 'Saúde Coletiva', 'Medidas', 'Incidência de doença rara em coorte de 10 anos.', 'Medida adequada?',
     '[{"text":"Densidade de incidência","is_correct":true},{"text":"Prevalência","is_correct":false},{"text":"Odds ratio","is_correct":false},{"text":"Razão de chances","is_correct":false},{"text":"Letalidade","is_correct":false}]'::jsonb,
     'Coorte com pessoa-tempo: densidade de incidência.'),
    (3, 'dificil', 'Saúde Mental', 'EQZ refratária', 'Sem resposta a 2 antipsicóticos em doses adequadas.', 'Próximo passo?',
     '[{"text":"Clozapina","is_correct":true},{"text":"Aumentar dose atual","is_correct":false},{"text":"TEC isolada","is_correct":false},{"text":"Benzo","is_correct":false},{"text":"Lítio","is_correct":false}]'::jsonb,
     'Refratariedade: clozapina com monitoramento.'),
    (3, 'dificil', 'Clínica Médica', 'AVC isquêmico', 'Mulher 65a, hemiparesia 2h, NIHSS 10, TC sem hemorragia.', 'Conduta?',
     '[{"text":"Trombólise com alteplase","is_correct":true},{"text":"AAS apenas","is_correct":false},{"text":"Anticoagulação plena","is_correct":false},{"text":"Aguardar 24h","is_correct":false},{"text":"Cirurgia","is_correct":false}]'::jsonb,
     'AVC <4,5h sem CI: trombólise.'),
    (3, 'dificil', 'GO', 'HPP atonia', 'Puérpera imediata, atonia uterina com sangramento maciço.', 'Primeira medida?',
     '[{"text":"Massagem + ocitocina","is_correct":true},{"text":"Histerectomia direta","is_correct":false},{"text":"Sutura B-Lynch de início","is_correct":false},{"text":"Embolização","is_correct":false},{"text":"Transfusão isolada","is_correct":false}]'::jsonb,
     'Atonia: ABC + massagem + ocitocina.'),
    (3, 'dificil', 'Pediatria', 'DRGE fisiológico', 'Lactente 4m, regurgitações, bom ganho ponderal, sem complicações.', 'Conduta?',
     '[{"text":"Orientar posição e aguardar","is_correct":true},{"text":"IBP empírico","is_correct":false},{"text":"Cirurgia antirrefluxo","is_correct":false},{"text":"Procinético","is_correct":false},{"text":"Fórmula AR obrigatória","is_correct":false}]'::jsonb,
     'DRGE fisiológico: orientações; evitar IBP.'),

    -- NÍVEL 4 — Muito Difícil
    (4, 'muito_dificil', 'Clínica Médica', 'Endocardite', 'UDEV, febre 10d, vegetação tricúspide, HMC S.aureus MSSA.', 'Tratamento?',
     '[{"text":"Oxacilina EV 4-6 sem","is_correct":true},{"text":"Vancomicina isolada","is_correct":false},{"text":"Ceftriaxona 2 sem","is_correct":false},{"text":"Só cirurgia","is_correct":false},{"text":"Apenas levofloxacino","is_correct":false}]'::jsonb,
     'EI por S. aureus MSSA: oxacilina EV 4-6 sem.'),
    (4, 'muito_dificil', 'Cirurgia', 'Volvo', 'Idoso 75a, grão de café em sigmoide, sem isquemia.', 'Conduta?',
     '[{"text":"Descompressão endoscópica","is_correct":true},{"text":"Laparotomia imediata","is_correct":false},{"text":"Conservador 7d","is_correct":false},{"text":"Enema opaco","is_correct":false},{"text":"Alta","is_correct":false}]'::jsonb,
     'Volvo sem isquemia: descompressão endoscópica.'),
    (4, 'muito_dificil', 'GO', 'Infertilidade', 'Casal 2 anos, 35a, ciclos regulares, espermograma e HSG normais.', 'Próximo passo?',
     '[{"text":"Reserva ovariana + indução","is_correct":true},{"text":"FIV direta","is_correct":false},{"text":"Só expectativa","is_correct":false},{"text":"Laparoscopia","is_correct":false},{"text":"Histeroscopia","is_correct":false}]'::jsonb,
     'Investigação sem causa: reserva ovariana e indução.'),
    (4, 'muito_dificil', 'Pediatria', 'Meningite', 'Criança 5a, LCR turvo, gram+ diplococos.', 'Empírico?',
     '[{"text":"Ceftriaxona + vancomicina","is_correct":true},{"text":"Só penicilina","is_correct":false},{"text":"Metronidazol","is_correct":false},{"text":"Oseltamivir","is_correct":false},{"text":"Aciclovir","is_correct":false}]'::jsonb,
     'Pneumococo suspeito: ceftriaxona + vanco.'),
    (4, 'muito_dificil', 'Med Família', 'Paliativo', 'Oncológico terminal, dor 8/10 refratária a AINE.', 'Conduta?',
     '[{"text":"Morfina titulada","is_correct":true},{"text":"Só paracetamol","is_correct":false},{"text":"Aguardar","is_correct":false},{"text":"Corticoide isolado","is_correct":false},{"text":"Sedação profunda","is_correct":false}]'::jsonb,
     'Dor oncológica moderada-grave: opioide forte.'),
    (4, 'muito_dificil', 'Saúde Coletiva', 'Vigilância', 'Caso suspeito de sarampo em UBS.', 'Conduta?',
     '[{"text":"Notificação imediata (24h) + isolamento","is_correct":true},{"text":"Aguardar laboratório","is_correct":false},{"text":"Só tratar","is_correct":false},{"text":"Esquecer","is_correct":false},{"text":"Notificar em 30 dias","is_correct":false}]'::jsonb,
     'Sarampo: notificação imediata.'),
    (4, 'muito_dificil', 'Saúde Mental', 'Risco suicídio', 'Paciente com plano, método e intenção.', 'Conduta?',
     '[{"text":"Internação (involuntária se recusar)","is_correct":true},{"text":"Alta com retorno","is_correct":false},{"text":"Só ISRS ambulatorial","is_correct":false},{"text":"Benzo e alta","is_correct":false},{"text":"Só família acompanhar","is_correct":false}]'::jsonb,
     'Risco iminente: internação.'),
    (4, 'muito_dificil', 'Clínica Médica', 'LRA + K', 'Séptico, Cr 3.5, oligúria, K 6.8 com alterações ECG.', 'Conduta?',
     '[{"text":"Diálise de urgência","is_correct":true},{"text":"Só furosemida","is_correct":false},{"text":"Gluconato de cálcio e observar","is_correct":false},{"text":"Bicarbonato EV isolado","is_correct":false},{"text":"Restrição hídrica só","is_correct":false}]'::jsonb,
     'Hipercalemia refratária com ECG: diálise.'),
    (4, 'muito_dificil', 'GO', 'CIN III', 'Mulher 45a, CIN III em biópsia, JEC visível.', 'Conduta?',
     '[{"text":"Conização","is_correct":true},{"text":"Histerectomia radical","is_correct":false},{"text":"Só seguimento","is_correct":false},{"text":"Crio isolada","is_correct":false},{"text":"RT primária","is_correct":false}]'::jsonb,
     'CIN III com JEC visível: conização.'),
    (4, 'muito_dificil', 'Pediatria', 'CAD', 'Criança DM1, pH 7.1, HCO3 8, K 3.2.', 'Inicial?',
     '[{"text":"Hidratação + insulina + reposição K","is_correct":true},{"text":"Insulina em bolus alto isolada","is_correct":false},{"text":"Bicarbonato EV rápido","is_correct":false},{"text":"Glicose EV","is_correct":false},{"text":"Só SF 0,45%","is_correct":false}]'::jsonb,
     'CAD: volume, insulina IV, repor K antes se <3.3.'),

    -- NÍVEL 5 — Tubarão
    (5, 'tubarao', 'Clínica Médica', 'Tireotóxica', 'Mulher 40a, Graves, T 40, FC 160, agitação, IC aguda.', 'Conduta?',
     '[{"text":"PTU + iodo + BB + corticoide","is_correct":true},{"text":"Só metimazol VO","is_correct":false},{"text":"Tireoidectomia imediata","is_correct":false},{"text":"Iodo radioativo","is_correct":false},{"text":"Só BB","is_correct":false}]'::jsonb,
     'Crise tireotóxica: PTU → iodo após 1h + BB + corticoide.'),
    (5, 'tubarao', 'Cirurgia', 'Pancreatite', 'Pancreatite biliar, APACHE 12, necrose infectada 3ª sem.', 'Conduta?',
     '[{"text":"Step-up: drenagem MI + ATB","is_correct":true},{"text":"Necrosectomia imediata","is_correct":false},{"text":"Só ATB 6 semanas","is_correct":false},{"text":"Cirurgia aberta na 1ª semana","is_correct":false},{"text":"CPRE isolada","is_correct":false}]'::jsonb,
     'Necrose infectada tardia: step-up approach.'),
    (5, 'tubarao', 'GO', 'Acretismo', 'Prévia + cesárea prévia, RM sugere acretismo em 36 sem.', 'Conduta?',
     '[{"text":"Cesárea-histerectomia programada","is_correct":true},{"text":"Parto vaginal","is_correct":false},{"text":"Cesárea comum e aguardar","is_correct":false},{"text":"Metotrexato","is_correct":false},{"text":"Só transfusão","is_correct":false}]'::jsonb,
     'Acretismo: cesárea-histerectomia programada.'),
    (5, 'tubarao', 'Pediatria', 'Kawasaki', 'Febre 7d, 2 critérios + PCR alta + plaq 600k.', 'Conduta?',
     '[{"text":"IVIG + AAS alta + ecocardio","is_correct":true},{"text":"Só AAS baixa","is_correct":false},{"text":"ATB empírico","is_correct":false},{"text":"Corticoide isolado","is_correct":false},{"text":"Observação","is_correct":false}]'::jsonb,
     'Kawasaki incompleta com lab sugestivo: tratar.'),
    (5, 'tubarao', 'Med Família', 'BRCA1', 'Mulher 35a, mãe e irmã com CA mama <50a, BRCA1+.', 'Conduta?',
     '[{"text":"RM mamas anual + discutir profilaxia","is_correct":true},{"text":"Mamo a cada 5 anos","is_correct":false},{"text":"Só USG","is_correct":false},{"text":"Aguardar 40 anos","is_correct":false},{"text":"Nenhuma intervenção","is_correct":false}]'::jsonb,
     'BRCA1+: rastreio intensivo e discutir profilaxia.'),
    (5, 'tubarao', 'Saúde Coletiva', 'Viés', 'Caso-controle: pacientes lembram exposição mais que controles.', 'Viés?',
     '[{"text":"Memória (recall bias)","is_correct":true},{"text":"Seleção","is_correct":false},{"text":"Confundimento","is_correct":false},{"text":"Aferição","is_correct":false},{"text":"Perda de seguimento","is_correct":false}]'::jsonb,
     'Recall bias típico em caso-controle.'),
    (5, 'tubarao', 'Saúde Mental', 'Catatonia', 'Mutismo, rigidez, negativismo, sem resposta a benzo.', 'Próximo passo?',
     '[{"text":"TEC","is_correct":true},{"text":"Aumentar benzo 2 sem","is_correct":false},{"text":"Antipsicótico típico isolado","is_correct":false},{"text":"Lítio","is_correct":false},{"text":"Só hidratação","is_correct":false}]'::jsonb,
     'Catatonia refratária a benzo: TEC.'),
    (5, 'tubarao', 'Clínica Médica', 'TEP maciço', 'Hipotenso, eco com disfunção VD, TC com TEP central.', 'Conduta?',
     '[{"text":"Trombólise sistêmica","is_correct":true},{"text":"Só HBPM","is_correct":false},{"text":"Filtro de VCI isolado","is_correct":false},{"text":"AAS","is_correct":false},{"text":"Observação","is_correct":false}]'::jsonb,
     'TEP alto risco: trombólise.'),
    (5, 'tubarao', 'GO', 'EAG', 'Gestante 36 sem, icterícia, coagulopatia, hipoglicemia, TGO 400.', 'Conduta?',
     '[{"text":"Interrupção imediata + suporte","is_correct":true},{"text":"Expectante até termo","is_correct":false},{"text":"Só corticoide","is_correct":false},{"text":"Plasmaférese primária","is_correct":false},{"text":"Transplante urgente","is_correct":false}]'::jsonb,
     'EAG: interrupção imediata.'),
    (5, 'tubarao', 'Pediatria', 'SCID', 'Lactente com infecções graves, linfopenia, ausência de timo.', 'Hipótese?',
     '[{"text":"SCID","is_correct":true},{"text":"HIV perinatal","is_correct":false},{"text":"Fibrose cística","is_correct":false},{"text":"Síndrome Job","is_correct":false},{"text":"Agamaglobulinemia ligada X","is_correct":false}]'::jsonb,
     'Linfopenia + ausência de timo: SCID.')
  ) AS t(lvl, diff, theme, subtopic, scen, q, opts, expl)
),
expanded AS (
  SELECT 
    t.*,
    v AS variant,
    ROW_NUMBER() OVER (PARTITION BY t.lvl ORDER BY v, t.subtopic) AS ord
  FROM templates t
  CROSS JOIN generate_series(1, 10) AS v
)
INSERT INTO public.simulado_questions (level, theme, scenario, question, options, difficulty, explanation, display_order)
SELECT 
  lvl,
  theme,
  CASE WHEN variant = 1 THEN '[' || subtopic || '] ' || scen
       ELSE '[' || subtopic || ' - variante ' || variant || '] ' || scen END,
  q,
  opts,
  diff,
  expl,
  ord::int
FROM expanded
ORDER BY lvl, ord;
